'use strict';

const nodeCrypto = require('crypto');

const SYSTEM_TAGS = Object.freeze([
  { id: 'capital', name: 'Capital', color: '#e1c471', description: 'Major political and industrial capital with the best rare-market access.' },
  { id: 'lostech', name: 'Lostech', color: '#72d6ff', description: 'System known for Star League caches, research enclaves, or rare technology.' },
  { id: 'pirate', name: 'Pirate', color: '#df6b72', description: 'System with a significant pirate, black-market, or raider presence.' },
]);

const CAPITAL_SYSTEMS = new Set([
  'Atreus',
  'Luthien',
  'New Avalon',
  'Sian',
  'Terra',
  'Tharkad',
]);

const DEFAULT_RARE_TEMPLATES = Object.freeze([
  {
    id: 'star-league-cooling-jacket',
    name: 'Star League Cooling Jacket',
    itemType: 'weapon',
    namePrefix: 'Star League',
    basePrice: 180000,
    description: 'An advanced thermal jacket recovered from a Star League cache.',
    modifiers: { heat: -1 },
  },
  {
    id: 'extended-barrel-prototype',
    name: 'Extended-Barrel Prototype',
    itemType: 'weapon',
    namePrefix: 'Extended-Range',
    basePrice: 220000,
    description: 'Precision barrel and targeting components extend every range bracket.',
    modifiers: { range: 1 },
  },
  {
    id: 'high-energy-capacitor',
    name: 'High-Energy Capacitor',
    itemType: 'weapon',
    namePrefix: 'Overcharged',
    basePrice: 260000,
    description: 'An experimental capacitor increases damage at the cost of additional heat.',
    modifiers: { damage: 1, heat: 1 },
  },
  {
    id: 'endo-composite-housing',
    name: 'Endo-Composite Weapon Housing',
    itemType: 'weapon',
    namePrefix: 'Lightweight',
    basePrice: 300000,
    description: 'Rare structural materials reduce the mounted weapon tonnage.',
    modifiers: { tonnage: -1 },
  },
  {
    id: 'prototype-guidance-package',
    name: 'Prototype Guidance Package',
    itemType: 'weapon',
    namePrefix: 'Precision',
    basePrice: 240000,
    description: 'Advanced fire-control electronics increase effective range and damage.',
    modifiers: { range: 1, damage: 1 },
  },
  {
    id: 'compact-support-assembly',
    name: 'Compact Support Assembly',
    itemType: 'equipment',
    namePrefix: 'Compact',
    basePrice: 160000,
    description: 'Miniaturized Star League components reduce installed equipment tonnage.',
    modifiers: { tonnage: -1 },
  },
  {
    id: 'advanced-thermal-module',
    name: 'Advanced Thermal Module',
    itemType: 'equipment',
    namePrefix: 'Advanced',
    basePrice: 140000,
    description: 'Rare heat-transfer components reduce heat generated by linked systems.',
    modifiers: { heat: -1 },
  },
]);

function slugify(value) {
  return String(value || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function deterministicFraction(value, salt = '') {
  const hex = nodeCrypto.createHash('sha256').update(`${salt}:${value}`).digest('hex').slice(0, 8);
  return Number.parseInt(hex, 16) / 0xffffffff;
}

function allocatedTags(system) {
  const tags = [];
  if (CAPITAL_SYSTEMS.has(system.name)) tags.push('capital');
  if (deterministicFraction(system._id, 'lostech-tag') < 0.05) tags.push('lostech');
  if (deterministicFraction(system._id, 'pirate-tag') < 0.01) tags.push('pirate');
  return tags;
}

function ensureSystemTags(store) {
  const update = store.db.transaction(() => {
    for (const system of store.list('system')) {
      if (Array.isArray(system.tags)) continue;
      store.put({ ...system, tags: allocatedTags(system) });
    }
  });
  update();
}

function ensureRareTemplates(store) {
  for (const template of DEFAULT_RARE_TEMPLATES) {
    const id = `rareItemTemplate:${template.id}`;
    if (!store.get(id)) store.put({ ...template, _id: id, _type: 'rareItemTemplate' });
  }
}

function rareChanceForTags(tags) {
  const values = Array.isArray(tags) ? tags : [];
  if (values.includes('capital')) return 0.6;
  if (values.includes('lostech')) return 0.3;
  if (values.includes('pirate')) return 0.15;
  return 0.02;
}

function numeric(value) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : 0;
}

function basicItemPrice(item, itemType) {
  if (itemType === 'equipment') {
    return 10000 + Math.round(deterministicFraction(item._id, 'equipment-price') * 15) * 1000;
  }
  const damage = numeric(item.totalDamage) || numeric(item.damagePerAttack);
  const range = numeric(item.range && item.range.long);
  const heat = numeric(item.heat);
  return Math.max(5000, Math.ceil((damage * 4500 + range * 900 + heat * 350) / 1000) * 1000);
}

function catalogItems(store, itemType) {
  const type = itemType === 'weapon' ? 'weapon' : 'equipment';
  return store.list(type)
    .filter(item => item.name)
    .sort((a, b) => String(a.name).localeCompare(String(b.name)));
}

function choose(values, seed, salt) {
  if (!values.length) return null;
  return values[Math.floor(deterministicFraction(seed, salt) * values.length)];
}

function createRareStock(store, system, generation = 1) {
  const templates = store.list('rareItemTemplate');
  const chance = rareChanceForTags(system.tags);
  const roll = deterministicFraction(system._id, `rare-roll-${generation}`);
  if (!templates.length || roll >= chance) return [];
  const count = 1 + Math.floor(deterministicFraction(system._id, `rare-count-${generation}`) * 3);
  const items = [];
  for (let index = 0; index < count; index++) {
    const seed = `${system._id}:${generation}:${index}`;
    const template = choose(templates, seed, 'template');
    if (!template) continue;
    const candidates = catalogItems(store, template.itemType);
    const requestedBase = template.baseItemName
      ? candidates.find(item => String(item.name).toLowerCase() === String(template.baseItemName).toLowerCase())
      : null;
    const baseItem = requestedBase || choose(candidates, seed, 'base-item');
    if (!baseItem) continue;
    const catalogPrice = basicItemPrice(baseItem, template.itemType);
    items.push({
      stockId: nodeCrypto.randomUUID(),
      templateId: template.id,
      templateName: template.name,
      itemType: template.itemType,
      baseItemId: baseItem._id,
      baseItemName: baseItem.name,
      name: `${template.namePrefix || 'Rare'} ${baseItem.name}`,
      description: template.description,
      modifiers: template.modifiers,
      price: Math.ceil((template.basePrice + catalogPrice * 4) / 1000) * 1000,
      rarity: 'Lostech',
    });
  }
  return items;
}

function marketId(system) {
  return `systemMarket:${system._id.replace(/^system:/, '')}`;
}

function generateSystemMarket(store, system, generation = 1) {
  const current = store.get(marketId(system));
  return store.put({
    ...(current || {}),
    _id: marketId(system),
    _type: 'systemMarket',
    systemId: system._id,
    systemName: system.name,
    generation,
    rareChance: rareChanceForTags(system.tags),
    rareItems: createRareStock(store, system, generation),
    rolledAt: new Date().toISOString(),
  });
}

function ensureSystemMarkets(store) {
  const createMissing = store.db.transaction(() => {
    for (const system of store.list('system')) {
      if (!store.get(marketId(system))) generateSystemMarket(store, system);
    }
  });
  createMissing();
}

function ensureMarketplace(store) {
  ensureRareTemplates(store);
  ensureSystemTags(store);
  ensureSystemMarkets(store);
}

function systemTagSummary(store) {
  const systems = store.list('system');
  const counts = Object.fromEntries(SYSTEM_TAGS.map(tag => [tag.id, 0]));
  for (const system of systems) {
    for (const tag of Array.isArray(system.tags) ? system.tags : []) {
      if (Object.hasOwn(counts, tag)) counts[tag]++;
    }
  }
  return { totalSystems: systems.length, tags: SYSTEM_TAGS, counts };
}

function balance(store) {
  return store.list('txn').reduce((sum, txn) => sum + (Number(txn.amount) || 0), 0);
}

function shopState(store) {
  const company = store.get('company:main') || {};
  const system = store.list('system').find(item => (
    String(item.name).toLowerCase() === String(company.currentSystem || '').toLowerCase()
  ));
  if (!system) throw new Error('Set a valid current system before shopping');
  const market = store.get(marketId(system)) || generateSystemMarket(store, system);
  const basic = {
    weapons: catalogItems(store, 'weapon').map(item => ({
      id: item._id,
      name: item.name,
      itemType: 'weapon',
      price: basicItemPrice(item, 'weapon'),
      heat: item.heat,
      damage: item.totalDamage || item.damagePerAttack,
      range: item.range || null,
    })),
    equipment: catalogItems(store, 'equipment').map(item => ({
      id: item._id,
      name: item.name,
      itemType: 'equipment',
      price: basicItemPrice(item, 'equipment'),
      description: item.description || '',
    })),
  };
  return {
    system: {
      id: system._id,
      name: system.name,
      affiliation: system.affiliation,
      tags: system.tags || [],
    },
    balance: balance(store),
    rareChance: market.rareChance,
    basic,
    rareItems: market.rareItems || [],
  };
}

module.exports = {
  DEFAULT_RARE_TEMPLATES,
  SYSTEM_TAGS,
  basicItemPrice,
  balance,
  ensureMarketplace,
  generateSystemMarket,
  marketId,
  rareChanceForTags,
  shopState,
  slugify,
  systemTagSummary,
};
